[package]
name = "port_sniffer"
version = "0.1.0"
authors = ["Amr A.Mohammed <merodiro@gmail.com>"]
description= "a port sniffer to detect open ports"
license = "MIT"

[dependencies]

[build-dependencies]
cc = { git = "https://github.com/alexcrichton/cc-rs" }
